### PR TITLE
Introducing hierarchical structure

### PR DESCRIPTION
**Pull request by reactorcoremeltdown**
Going further on retrofitting wikmd into my existing wiki repository.

Didn't want to store my cat's health info in the same directory as heating meters readings, so here's the change.

One needs to specify a path to page to create one alongside with directory tree.

image

Also adjusted templates to fix routing issues.

This is somewhat a major change, so please feel free to decline if that doesn't fit into wikmd's development plan!

### CODE REVIEW

**Comment by Linbreux** [comment]
Hi, this is something that would make the wiki great, I was thinking on implementing this. Thanks for the PR. The only problem is that it does not show in the search results. Could you implement this? Otherwise, I'll implement this in the course of next week.

**Comment by reactorcoremeltdown** [comment]
Hi @Linbreux !

Just made recursive search working, please have a look and suggest edits when you have a moment!

Searching for my cat's name in my wiki returned expected results, so I assume it works :)

image

Please let me know if anything looks confusing! Have a great weekend.

**Comment by Linbreux** [comment]
@reactorcoremeltdown perfect! If you have any additional ideas or requests, feel free to share them!

**Comment by reactorcoremeltdown** [comment]
@Linbreux thanks a lot!

What's on my list:
+ Using codemirror for textarea for more typing pleasure (continuing lists, blockquotes, tab indentation) — already implemented, can send a pull request, needs testing though
+ Custom homepage filename using an environment variable (a large number of repos start with README.md) — implemented, can send a pull request
+ Picking up custom CSS from the repository root — going to implement over the course of the next week
+ i18n based on Accept-Language header — questionable, highly optional, don't even think this might work, but maybe worth trying

**Comment by Linbreux** [comment]
Alright I think this would fit the scope of the project. If you got something feel free to create a PR. Currently I'm working on something that lets a user list al the files of a givin folder.

**Pull request merged**
