### PR TITLE
Update Import hashes

### PR DESCRIPTION
**Pull request by Archef2000**
### Summary
Update Import hashes

### Details
New hashes of imported stylesheets

### Checks
- [ ] In case of new feature, add short overview in ```docs/<corresponding file>``` 
- [x] Tested changes

### CODE REVIEW

**Comment by Archef2000** [comment]
Python Version 3.6 with arch x64 not found in the check

**Comment by Linbreux** [comment]
Hi @Archef2000, Thanks for the PR! Could you give a little more information? What problem does this fix?

**Comment by Archef2000** [comment]
grafik
It fixes the wrong integrity hashes

**Comment by Linbreux** [comment]
@Archef2000 alright! Thanks. Did you also test it on a native system? With this PR I get the following: 

image

**Comment by Archef2000** [comment]
Sorry my me being dumb i had a addon causing the problem called LocalCDN.
A seperate question using wikmd for a while how would aou like it if the would be a way that you could write Markdown and view it with a preview tab and having all files local so it even would work for an offline system.

**Comment by Linbreux** [comment]
@Archef2000, alright, no problem :smile: 

>A seperate question using wikmd for a while how would aou like it if the would be a way that you could write Markdown and view it with a preview tab and having all files local so it even would work for an offline system.

I'm not yet fully sold on this, the page needs to be rendered constantly which would take a lot of processing power and make the UI feel slow. Also, I find the code editor we use pretty good at giving a 'preview'. But be my guest to try something and I'll check it out!

**Pull request closed without merging**
